name: Build & tests
on: push
jobs:
  check-on-push:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check
